[env:custom_build]
extends = env:esp32s3dev_8MB_PSRAM
build_flags = ${env:esp32s3dev_8MB_PSRAM.build_flags} -D WLED_DISABLE_BROWNOUT_DET -D LEDPIN=16 -D USERMOD_DHT -D USERMOD_DHT_CELSIUS -D USERMOD_FOUR_LINE_DISPLAY -D USERMOD_PING_PONG_CLOCK -D USERMOD_WORDCLOCK -D USERMOD_ANALOG_CLOCK
lib_deps = 
  ${env:esp32s3dev_8MB_PSRAM.lib_deps}
  https://github.com/alwynallan/DHT_nonblocking
  olikraus/U8g2 @ ^2.28.8
