name: WLED-MM compile (ESP32-WROOM)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Fetch MoonModules WLED (mdev)
        run: |
          set -euxo pipefail
          git clone --depth 1 --branch mdev https://github.com/MoonModules/WLED-MM.git /tmp/WLED-MM
          echo "/tmp/WLED-MM" > /tmp/WLED_DIR

      - name: Pick base env for ESP32-WROOM (4MB)
        id: envpick
        run: |
          set -euxo pipefail
          cd "$(cat /tmp/WLED_DIR)"
          # Prefer MoonModules' 4MB env if present, fall back to esp32dev if not.
          if grep -q "^\[env:esp32_4MB_max\]" platformio.ini; then
            echo "BASE_ENV=esp32_4MB_max" >> $GITHUB_OUTPUT
          elif grep -q "^\[env:esp32dev\]" platformio.ini; then
            echo "BASE_ENV=esp32dev" >> $GITHUB_OUTPUT
          else
            echo "Could not find a suitable base env in platformio.ini"; exit 1
          fi

      - name: Add custom env for WROOM build
        run: |
          set -euxo pipefail
          cd "$(cat /tmp/WLED_DIR)"
          BASE_ENV="${{ steps.envpick.outputs.BASE_ENV }}"
          {
            echo ""
            echo "[env:custom_wroom]"
            echo "extends = env:${BASE_ENV}"
            # Keep MM defaults, add only minimal overrides you actually need.
            # Example LED pin override; change or drop if not needed:
            echo "build_flags = \${env:${BASE_ENV}.build_flags} -D LEDPIN=16"
            echo "lib_deps ="
            echo "  \${env:${BASE_ENV}.lib_deps}"
          } >> platformio.ini

      - name: Build firmware (custom_wroom)
        run: |
          set -euxo pipefail
          cd "$(cat /tmp/WLED_DIR)"
          pio run -e custom_wroom
          # Prefer WLED's export layout if present, fallback to pio default
          BIN=$(ls build_output/firmware/custom_wroom*.bin 2>/dev/null || true)
          if [ -z "$BIN" ]; then BIN=.pio/build/custom_wroom/firmware.bin; fi
          cp "$BIN" "$GITHUB_WORKSPACE/WLED-MM_custom_wroom.bin"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WLED-MM_custom_wroom
          path: WLED-MM_custom_wroom.bin

